# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${IOS_POSTGRES_PASSWORD}
      POSTGRES_USER: ${IOS_POSTGRES_USER}
      POSTGRES_DB: ${IOS_POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 1s
    networks:
      - proxy

  api:
    build: .
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - proxy

volumes:
  db-data:
networks:
  proxy:
    external: true
